# Site settings
title: Module POO ARIC
description: > # this means to ignore newlines until "baseurl:"
  Support des travaux pratiques du module de Programmation Orientée Objet en Java du département GEII de l'IUT Lyon 1.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://geiilyon.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md

collections:
  collection_enonces:
    output: true
    permalink: /enonces/:name/
